spring:
  datasource:
    url: jdbc:mysql://121.37.12.183:6603/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: wylzs8888
  elasticsearch:
    uris: 121.37.12.183:9200
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: 121.37.12.183